## ------------------------------------- ##
## Check for modern C++ compiler support ##
## ------------------------------------- ##
include(CheckCXXCompilerFlag)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++17")
if (CMAKE_COMPILER_IS_GNUCXX)
  CHECK_CXX_COMPILER_FLAG("-std=c++17" COMPILER_SUPPORTS_CXX17)
  CHECK_CXX_COMPILER_FLAG("-std=c++14" COMPILER_SUPPORTS_CXX14)
  CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
  CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
  if(COMPILER_SUPPORTS_CXX17)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
	message(STATUS "The compiler ${CMAKE_CXX_COMPILER} supports C++17.")
  elseif(COMPILER_SUPPORTS_CXX14)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
	message(STATUS "The compiler ${CMAKE_CXX_COMPILER} supports C++14.")
  elseif(COMPILER_SUPPORTS_CXX11)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
	message(STATUS "The compiler ${CMAKE_CXX_COMPILER} supports C++11.")
  elseif(COMPILER_SUPPORTS_CXX0X)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
	message(STATUS "The compiler ${CMAKE_CXX_COMPILER} supports C++0x.")
  else()
	message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no modern C++ support. Please use a different C++ compiler.")
  endif()
endif()
